services:
  aggregator:
    build:
      context: .
      args:
        GO_VERSION: ${GO_VERSION}
    ports:
      - "${AGG_PORT}:${AGG_PORT}"
    environment:
      - METRICS_AGGREGATOR_PORT=${AGG_PORT}
      - METRICS_ENDPOINTS={"prometheus1":"http://prometheus1:${PROM_PORT}/metrics","prometheus2":"http://prometheus2:${PROM_PORT}/metrics"}
    depends_on:
      - prometheus1
      - prometheus2

  prometheus1:
    image: prom/prometheus:latest
    ports:
      - "${PROM1_EXT}:${PROM_PORT}"
    environment:
      - PROM_PORT=${PROM_PORT}
    volumes:
      - ./prometheus1.yml:/etc/prometheus/prometheus.yml

  prometheus2:
    image: prom/prometheus:latest
    ports:
      - "${PROM2_EXT}:${PROM_PORT}"
    environment:
      - PROM_PORT=${PROM_PORT}
    volumes:
      - ./prometheus2.yml:/etc/prometheus/prometheus.yml
