name: Compose smoke test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  compose-test:
    runs-on: ubuntu-latest
    permissions: {contents: read}

    steps:
      - uses: actions/checkout@v4

      # .env file makes the ports available to Compose
      - name: Show env
        run: cat .env

      - uses: docker/setup-buildx-action@v3

      - name: docker compose config
        run: docker compose config

      - name: docker compose up
        run: docker compose up -d --wait

      - name: Probe aggregator /metrics
        run: |
          for i in {1..10}; do
            if curl -fs http://localhost:${{ env.AGG_PORT }}/metrics >/dev/null; then
              echo "Aggregator is healthy"; exit 0
            fi
            echo "waiting…"; sleep 2
          done
          echo "Aggregator never came up"; exit 1
        env:
          AGG_PORT: ${{ env.AGG_PORT }}

      - name: Probe Prometheus instances
        run: |
          curl -f http://localhost:${{ env.PROM1_EXT }}/-/healthy
          curl -f http://localhost:${{ env.PROM2_EXT }}/-/healthy
        env:
          PROM1_EXT: ${{ env.PROM1_EXT }}
          PROM2_EXT: ${{ env.PROM2_EXT }}

      - name: docker compose down
        if: always()
        run: docker compose down -v
