name: Compose smoke test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  compose-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read          # checkout only

    steps:
      # 1 ── checkout repo
      - uses: actions/checkout@v4

      # 2 ── validate syntax & interpolations with native CLI
      - name: docker compose config
        run: docker compose -f docker-compose.yaml config

      # 3 ── build & start all services
      - uses: docker/setup-buildx-action@v3     # build cache / BuildKit
      - name: docker compose up
        run: docker compose -f docker-compose.yaml up -d --wait

      # 4 ── probe aggregator
      - name: Probe aggregator /metrics
        run: |
          for i in {1..10}; do
            if curl -fs http://localhost:8080/metrics > /dev/null; then
              echo "Aggregator is healthy"; exit 0
            fi
            echo "waiting for aggregator…"; sleep 2
          done
          echo "Aggregator never came up"; exit 1
      # 5 ── probe Prometheus instances
      - name: Probe Prometheus instances
        run: |
          curl -f http://localhost:9091/-/healthy
          curl -f http://localhost:9092/-/healthy
      # 6 ── tear down (always runs, even on failure)
      - name: docker compose down
        if: always()
        run: docker compose -f docker-compose.yaml down -v
