name: Lint & vuln scan

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # ① checkout
      - uses: actions/checkout@v4

      # ② setup Go (follows go.mod; 1.24 in your case)
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      # ③ install Staticcheck
      - name: Install Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      # ④ install Revive
      - name: Install Revive
        run: |
          go install github.com/mgechev/revive@latest
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      # ⑤ run Staticcheck
      - name: Run Staticcheck
        run: staticcheck ./...

      # ⑥ run Revive with default config (warn only)
      - name: Run Revive
        run: revive -formatter friendly ./...

      - uses: golang/govulncheck-action@v1
