name: Lint & vuln scan
on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      # Install the v2 binary into $HOME/bin
      - name: Install golangci-lint v2.2.1
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b $HOME/bin v2.2.1
          ls -l $HOME/bin   # debugging: shows golangci-lint

      # Call the binary with its absolute path
      - name: Run golangci-lint v2
        run: |
          $HOME/bin/golangci-lint run --format=github-actions --timeout=5m

      - uses: golang/govulncheck-action@v1
