name: Lint & vuln scan

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Install Go 1.24 (or whatever is in go.mod)
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod   # go 1.24
          cache: true

      # 3. Build golangci-lint v1.59.0 from source with Go 1.24
      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.59.0
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
          golangci-lint --version

      # 4. Run the linter with the new flag name
      - name: Run golangci-lint
        run: golangci-lint run --timeout=5m

      - uses: golang/govulncheck-action@v1
