name: Lint & vuln scan

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run golangci-lint v1.54.2
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54.2
          args: --timeout=5m

      - uses: golang/govulncheck-action@v1
