name: Test & Coverage
on:
  push:
    branches: [main]          # build every commit on default branch
  pull_request:               # and every PR

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: {contents: read}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run unit-tests
        run: |
          go test -race -coverprofile=cover.out ./...
          go tool cover -html=cover.out -o cover.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: cover.html
          retention-days: 7

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: cover.out
          flags: unittests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
